apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: OrderItem
  template:
    metadata:
      labels:
        app: OrderItem
    spec:
      containers:
      - name:   orderitem
        image: truymcr.azurecr.io/orderrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ordersn

---
apiVersion: v1
kind: Service
metadata:
  name: menuitemlisting
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: OrderItem